spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Product-Data-Management-System
    username: postgres
    password: postgres
      

mybatis:
  configuration:
    map-underscore-to-camel-case: true


